# Generated by Django 5.1.1 on 2024-09-26 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Changed at')),
                ('name', models.CharField(max_length=255, verbose_name='Компания')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Changed at')),
                ('position_name', models.CharField(max_length=255, verbose_name='Позиция')),
                ('salary_start', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата начало')),
                ('salary_end', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата конец')),
                ('required_experience_year_start', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Опыт начало')),
                ('required_experience_year_end', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Опыт конец')),
                ('position_description', models.TextField(verbose_name='Текст вакансии')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company', verbose_name='Компания')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
