# Generated by Django 5.1.1 on 2024-09-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_country_street_city_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': '[a1] Вакансия', 'verbose_name_plural': '[a1] Вакансии'},
        ),
    ]
