# Generated by Django 5.1.1 on 2024-09-30 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_vacancy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.location', verbose_name='Локация компании'),
            preserve_default=False,
        ),
    ]
