# Generated by Django 5.1.1 on 2024-10-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_vacancy_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='technology',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='technology',
            field=models.ManyToManyField(blank=True, to='app.technology', verbose_name='Технология'),
        ),
    ]
